spring.application.name=monitor-app

#spring.rabbitmq.host = localhost
spring.rabbitmq.host = rabbitmq
spring.rabbitmq.port = 5672
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest

rabbitmq.queue.name = test_queue
rabbitmq.exchange.name = consumption_exchange
rabbitmq.routing.key = consumption_routing_key

rabbitmq.devices-queue.name = devices_queue


###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
#backend_db_2 instead of localhost
#spring.datasource.url = jdbc:mysql://localhost:3306/sd_2
spring.datasource.url = jdbc:mysql://monitor_db:3306/monitor_db
spring.datasource.username = root
spring.datasource.password = utcnJoke

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true

server.tomcat.threads.max = 1
###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=error
logging.level.org.springframework=error
logging.level.ro.tuc=error


###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
#pt docker
server.port=${PORT:8085}
server.forward-headers-strategy=NONE
